name: MFP Wealth Management
favicon: null
layout_spectrum: 0.82151
typography_spectrum: 0.8569836374372244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b2d3f'
    - '#64676b'
    - '#000000'
    - '#550000'
    - '#800000'
  brandStrength: 0.9375
  lightness: 0.29408612265251577
  saturation: 0.41078240470960736
  rhythmicContrast: 0.4778594905510545
purpose: []
